/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class LoadViewUI extends Laya.View {
		public progressBar:Laya.ProgressBar;
		public percentValue:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":640,"runtime":"script/LoadView.ts","height":1136},"compId":2,"child":[{"type":"ProgressBar","props":{"y":804,"x":104,"width":458,"var":"progressBar","skin":"comp/progress.png","height":40},"compId":3,"child":[{"type":"Label","props":{"y":5,"x":189,"var":"percentValue","text":"100%","fontSize":30,"font":"Arial","color":"#0e57f3","bold":true},"compId":6}]},{"type":"Label","props":{"y":757,"x":104,"text":"资源加载中...","fontSize":30,"font":"Arial","color":"#f9f6f6","bold":true},"compId":4}],"loadList":["comp/progress.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadViewUI.uiView);
        }
    }
    export class MainSceneUI extends Laya.Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":640,"runtime":"script/MainScene.ts","height":1136},"compId":2,"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(MainSceneUI.uiView);
        }
    }
    export class MainViewUI extends Laya.View {
		public btn1:Laya.Button;
		public btn2:Laya.Button;
		public btn3:Laya.Button;
		public btn4:Laya.Button;
        public static  uiView:any ={"type":"View","props":{"width":640,"runtime":"script/MainView.ts","height":1136},"compId":2,"child":[{"type":"Button","props":{"y":151,"x":502,"var":"btn1","skin":"comp/button.png","name":"1","label":"label","height":40},"compId":6},{"type":"Button","props":{"y":219,"x":503,"var":"btn2","skin":"comp/button.png","name":"2","label":"label","height":40},"compId":7},{"type":"Button","props":{"y":281,"x":503,"var":"btn3","skin":"comp/button.png","name":"3","label":"label","height":40},"compId":8},{"type":"Button","props":{"y":345,"x":503,"var":"btn4","skin":"comp/button.png","name":"4","label":"label","height":40},"compId":9}],"loadList":["comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(MainViewUI.uiView);
        }
    }
}