/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LoadView from "./script/LoadView"
import MainScene from "./script/MainScene"
import MainView from "./script/MainView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/LoadView.ts",LoadView);
        reg("script/MainScene.ts",MainScene);
        reg("script/MainView.ts",MainView);
    }
}
GameConfig.init();